#!/bin/bash
# more infos here --> https://blog.omgmog.net/post/compressing-pdf-from-your-mac-or-linux-terminal-with-ghostscript/
if [ "$#" -eq 0 ]
then
    echo "Usage: compresspdf [input file] [output file] [screen*|ebook|printer|prepress]"
    exit 1
else
    gs -sDEVICE=pdfwrite -dNOPAUSE -dQUIET -dBATCH -dPDFSETTINGS=/${3:-"screen"} -dCompatibilityLevel=1.4 -sOutputFile=$2 $1
fi
