#!/bin/bash
#npm install -g npm@latest

INSTALL_NPM='npm install -g'
#YARN=$(which yarn)
#if [ -n "$YARN" ]
#then
    #INSTALL_NPM="$YARN global add"
#fi

$INSTALL_NPM \
    npm@latest \
    eslint@latest \
    corepack@latest \
    typescript@latest \
    typescript-language-server@latest \
    prettier@latest \
    prettier-plugin-astro@latest \
    stylelint@latest \
    @vtsls/language-server@latest \
    @astrojs/language-server \
    yaml-language-server@latest \
    @ansible/ansible-language-server@latest \
    dockerfile-language-server-nodejs@latest \
    @microsoft/compose-language-service@latest \
    vscode-langservers-extracted@latest \
    neovim@latest

    # tsc@latest \
    #
    # gulp-cli@latest \
    # postcss@latest \
    # standard@latest \
    # @babel/cli@latest @babel/core@latest @babel/eslint-parser@latest \
    # gatsby-cli@latest \
    # lerna@latest \
    # tern@latest
    # jsonlint@latest \
    # csscomb@latest \
    # json2yaml@latest \
    # babel-eslint@latest \
    # deepl-translator-cli@latest \
    # prettier@latest prettier-eslint@latest prettier-standard@latest \
    # eslint-config-airbnb@latest \
    # eslint-plugin-react-hooks@latest \
    # eslint-plugin-import@latest \
    # eslint-plugin-jsx-a11y@latest \
    # eslint-plugin-react@latest \
    # eslint-plugin-standard@latest \
    # eslint-plugin-graphql@latest graphql@^0.13 \
    # eslint-plugin-typescript@latest \
    # flow-bin@latest \
    # avn avn-nvm \
    # pug-lint@latest \
    # htmlhint@latest \
    # sass-lint@latest \
    # jscs@latest \
    # jshint@latest \
    # serve@latest \
    # @typescript-eslint/parser \
    # grunt-cli@latest \
    # tslint@latest \

