#!/bin/bash
#npm install -g npm@latest

INSTALL_NPM='npm install -g'
#YARN=$(which yarn)
#if [ -n "$YARN" ]
#then
    #INSTALL_NPM="$YARN global add"
#fi

$INSTALL_NPM \
    eslint@latest \
    @babel/cli@latest @babel/core@latest @babel/eslint-parser@latest \
    postcss@latest \
    typescript@latest \
    prettier@latest \
    standard@latest \
    stylelint@latest \
    gulp-cli@latest \

    # gatsby-cli@latest \
    # lerna@latest \
    # tern@latest
    # jsonlint@latest \
    # csscomb@latest \
    # json2yaml@latest \
    # babel-eslint@latest \
    # deepl-translator-cli@latest \
    # prettier@latest prettier-eslint@latest prettier-standard@latest \
    # eslint-config-airbnb@latest \
    # eslint-plugin-react-hooks@latest \
    # eslint-plugin-import@latest \
    # eslint-plugin-jsx-a11y@latest \
    # eslint-plugin-react@latest \
    # eslint-plugin-standard@latest \
    # eslint-plugin-graphql@latest graphql@^0.13 \
    # eslint-plugin-typescript@latest \
    # flow-bin@latest \
    # avn avn-nvm \
    # pug-lint@latest \
    # htmlhint@latest \
    # sass-lint@latest \
    # jscs@latest \
    # jshint@latest \
    # serve@latest \
    # @typescript-eslint/parser \
    # grunt-cli@latest \
    # tslint@latest \

