#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Keine Root-Rechte erkannt. Starte neu mit sudo..."
  exec sudo "$0" "$@"
fi

for mirror in /etc/pacman.d/mirrorlist /etc/pacman.d/cachyos-mirrorlist /etc/pacman.d/cachyos-v3-mirrorlist /etc/pacman.d/cachyos-v4-mirrorlist; do
  if [ -f ${mirror}.pacnew ]; then
    set -x
    cp ${mirror} ${mirror}-backup
    cp ${mirror}.pacnew ${mirror}
    rm ${mirror}.pacnew
    set +x
    echo "++ Die Mirrorlist ${mirror} wurde erfolgreich aktualisiert und die alten Mirrorlist gesichert."
  fi
done

exec cachyos-rate-mirrors
